apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-templates-parsing
  namespace: golangtemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-templates-parsing
  template:
    metadata:
      labels:
        app: golang-templates-parsing
    spec:
      containers:
        - name: go-temp-parsing
          image: rayeneamina/go-temp-parsing:0.0.3
          ports:
            - containerPort: 8085
