apiVersion: v1
kind: Service
metadata:
  name: golang-templates-parsing
  namespace: golangtemp
spec:
  selector:
    app: golang-templates-parsing
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort

