apiVersion: v1
kind: Service
metadata:
  name: golang-templates-parsing
  namespace: golangtemp
spec:
  selector:
    app: golang-templates-parsing
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

